#!/bin/bash
set -x

MAIN_NS="net1 net2 zoo1 zoo2"
MAIN_BRIDGE_NAME=br0
MAIN_BRIDGE_IP=10.0.0.240/24

source ./functions

start_testbed() {
    echo "Starting main bridge"
    start_bridge $MAIN_BRIDGE_NAME $MAIN_BRIDGE_IP
    
    net1 start
    net2 start
    zoo1 start
    zoo2 start
}

start_testbed() {
    stop_net1
    stop_net2
    stop_zoo1
    stop_zoo2
    
    echo "Stopping main bridge"
    stop_bridge $MAIN_BRIDGE_NAME
}

start_net1() {

    NS_NAME=net1
    MAIN_IFACE_IP=10.0.0.3/24

    VM_BRIDGE1_NAME=$NS_NAME-br1
    VM_BRIDGE1_IP=172.16.0.240/24

    VM_BRIDGE2_NAME=$NS_NAME-br2
    VM_BRIDGE2_IP=172.16.1.240/24

    case $1 in
	start)
	    start_host net1 $MAIN_IFACE_IP $MAIN_BRIDGE_NAME $MAIN_BRIDGE_IP

	    echo "Starting virtual bridge $VM_BRIDGE1_NAME"
	    start_bridge $VM_BRIDGE1_NAME $VM_BRIDGE1_IP net1

	    echo "Starting virtual bridge $VM_BRIDGE2_NAME"
	    start_bridge $VM_BRIDGE2_NAME $VM_BRIDGE2_IP net1

	    start_vm net1 net1.1 172.16.0.101/24 172.16.0.240 $VM_BRIDGE1_NAME
	    start_vm net1 net1.2 172.16.0.102/24 172.16.0.240 $VM_BRIDGE1_NAME
	    start_vm net1 net1.3 172.16.0.103/24 172.16.0.240 $VM_BRIDGE1_NAME

	    start_vm net1 net1.4 172.16.1.101/24 172.16.1.240 $VM_BRIDGE2_NAME
	    start_vm net1 net1.5 172.16.1.102/24 172.16.1.240 $VM_BRIDGE2_NAME
	    ;;

stop_net1() {

    stop_host net1 $MAIN_BRIDGE_NAME

    stop_vm net1.1
    stop_vm net1.2
    stop_vm net1.3
    
    stop_vm net1.4
    stop_vm net1.5
    
    echo "Stopping virtual bridge $VM_BRIDGE1_NAME"
    stop_bridge $VM_BRIDGE1_NAME net1
    
    echo "Stopping virtual bridge $VM_BRIDGE2_NAME"
    stop_bridge $VM_BRIDGE2_NAME net1

	    ;;
    esac

}

start_net2() {
    NS_NAME=net2
    MAIN_IFACE_IP=10.0.0.4/24
    
    VM_BRIDGE1_NAME=$NS_NAME-br1
    VM_BRIDGE1_IP=172.16.2.240/24

    case $1 in
	start)
	    start_host $NS_NAME $MAIN_IFACE_IP $MAIN_BRIDGE_NAME $MAIN_BRIDGE_IP
	    
	    echo "Starting virtual bridge $VM_BRIDGE1_NAME"
	    start_bridge $VM_BRIDGE1_NAME $VM_BRIDGE1_IP $NS_NAME
	    
	    start_vm $NS_NAME $NS_NAME.1 172.16.2.101/24 172.16.0.240 $VM_BRIDGE1_NAME
	    start_vm $NS_NAME $NS_NAME.2 172.16.2.102/24 172.16.0.240 $VM_BRIDGE1_NAME
	    ;;
	
	stop)
	    stop_host $NS_NAME $MAIN_BRIDGE_NAME
	    
	    stop_vm $NS_NAME.1
	    stop_vm $NS_NAME.2
	    
	    echo "Stopping virtual bridge $VM_BRIDGE1_NAME"
	    stop_bridge $VM_BRIDGE1_NAME $NS_NAME
	    
	    ;;
    esac
}

start_zoo1() {
    NS_NAME=zoo1
    MAIN_IFACE_IP=10.0.0.5/24
    
    case $1 in
	start)
	    start_host $NS_NAME $MAIN_IFACE_IP $MAIN_BRIDGE_NAME $MAIN_BRIDGE_IP
	    ;;
	
	stop)
	    stop_host $NS_NAME $MAIN_BRIDGE_NAME
	    ;;
    esac
}

start_zoo2() {
    NS_NAME=zoo2
    MAIN_IFACE_IP=10.0.0.4/24
    
    case $1 in
	start)
	    start_host $NS_NAME $MAIN_IFACE_IP $MAIN_BRIDGE_NAME $MAIN_BRIDGE_IP
	    ;;
	
	stop)
	    stop_host $NS_NAME $MAIN_BRIDGE_NAME
	    ;;
    esac
}



case $1 in
    start)
	testbed start
	;;

    stop)
	testbed stop
	;;

    *)

	echo "Usage: $0 {start|stop}"
	;;

esac
