#!/bin/bash

set -x

source ./testenv.conf
source ./functions

NS_NAME=net1
MAIN_IFACE_IP=10.0.0.3/24

VM_BRIDGE1_NAME=$NS_NAME-br1
VM_BRIDGE1_IP=172.16.0.240/24

VM_BRIDGE2_NAME=$NS_NAME-br2
VM_BRIDGE2_IP=172.16.1.240/24

case $1 in
  start)
    start_host $NS_NAME $MAIN_IFACE_IP

    echo "Starting virtual bridge $VM_BRIDGE1_NAME"
    start_bridge $VM_BRIDGE1_NAME $VM_BRIDGE1_IP $NS_NAME

    echo "Starting virtual bridge $VM_BRIDGE2_NAME"
    start_bridge $VM_BRIDGE2_NAME $VM_BRIDGE2_IP $NS_NAME

    start_vm $NS_NAME $NS_NAME.1 172.16.0.101/24 172.16.0.240 $VM_BRIDGE1_NAME
    start_vm $NS_NAME $NS_NAME.2 172.16.0.102/24 172.16.0.240 $VM_BRIDGE1_NAME
    start_vm $NS_NAME $NS_NAME.3 172.16.0.103/24 172.16.0.240 $VM_BRIDGE1_NAME

    start_vm $NS_NAME $NS_NAME.4 172.16.1.101/24 172.16.1.240 $VM_BRIDGE2_NAME
    start_vm $NS_NAME $NS_NAME.5 172.16.1.102/24 172.16.1.240 $VM_BRIDGE2_NAME
    ;;

  stop)
    stop_host $NS_NAME

    stop_vm $NS_NAME.1
    stop_vm $NS_NAME.2
    stop_vm $NS_NAME.3

    stop_vm $NS_NAME.4
    stop_vm $NS_NAME.5

    echo "Stopping virtual bridge $VM_BRIDGE1_NAME"
    stop_bridge $VM_BRIDGE1_NAME $NS_NAME

    echo "Stopping virtual bridge $VM_BRIDGE2_NAME"
    stop_bridge $VM_BRIDGE2_NAME $NS_NAME

    ;;
  *)
    echo "Usage: $0 {start|stop}"
    ;;
esac

