#!/bin/bash

set -x

source ./testenv.conf
source ./functions

NS_NAME=net2
MAIN_IFACE_IP=10.0.0.4/24

VM_BRIDGE1_NAME=$NS_NAME-br1
VM_BRIDGE1_IP=172.16.2.240/24

case $1 in
  start)
    start_host $NS_NAME $MAIN_IFACE_IP $MAIN_BRIDGE_NAME $MAIN_BRIDGE_IP

    echo "Starting virtual bridge $VM_BRIDGE1_NAME"
    start_bridge $VM_BRIDGE1_NAME $VM_BRIDGE1_IP $NS_NAME

    start_vm $NS_NAME $NS_NAME.1 172.16.2.101/24 172.16.0.240 $VM_BRIDGE1_NAME
    start_vm $NS_NAME $NS_NAME.2 172.16.2.102/24 172.16.0.240 $VM_BRIDGE1_NAME
    ;;

  stop)
    stop_host $NS_NAME

    stop_vm $NS_NAME.1
    stop_vm $NS_NAME.2

    echo "Stopping virtual bridge $VM_BRIDGE1_NAME"
    stop_bridge $VM_BRIDGE1_NAME $NS_NAME

    ;;
  *)
    echo "Usage: $0 {start|stop}"
    ;;
esac

